### ISSUE TITLE
Error Reading from database in Moodle 3.1.5

### ISSUE THREAD

**Issue by SergioComeron** [vfremaux/moodle-block_use_stats#10]
I install the pluging in Moodle v: 3.1.5. with a postgreSQL database but when I go to put the use stats block on the course, Moodle return the following error:

> Debug info: ERROR: argument of OR must be type boolean, not type integer
> LINE 20: (1
> ^
> 
> SELECT
> id,
> courseid as course,
> action,
> target,
> timecreated as time,
> userid,
> contextid,
> contextinstanceid,
> contextlevel
> FROM
> mdl_logstore_standard_log
> WHERE
> origin != 'cli' AND
> timecreated > $1 AND
> timecreated < $2 AND
> ((courseid = 0 AND action = 'loggedin') OR
> (courseid = 0 AND action = 'loggedout') OR
> (1
> ))
> AND userid = 15583 AND realuserid IS NULL
> ORDER BY
> timecreated
> 
> [array (
> 0 => 1488785538,
> 1 => 1493969538,
> )]
> Error code: dmlreadexception
> Stack trace:
> line 479 of /lib/dml/moodle_database.php: dml_read_exception thrown
> line 250 of /lib/dml/pgsql_native_moodle_database.php: call to moodle_database->query_end()
> line 759 of /lib/dml/pgsql_native_moodle_database.php: call to pgsql_native_moodle_database->query_end()
> line 206 of /blocks/use_stats/locallib.php: call to pgsql_native_moodle_database->get_recordset_sql()
> line 153 of /blocks/use_stats/block_use_stats.php: call to use_stats_extract_logs()
> line 288 of /blocks/moodleblock.class.php: call to block_use_stats->get_content()
> line 230 of /blocks/moodleblock.class.php: call to block_base->formatted_contents()
> line 976 of /lib/blocklib.php: call to block_base->get_content_for_output()
> line 1028 of /lib/blocklib.php: call to block_manager->create_block_contents()
> line 476 of /lib/outputrenderers.php: call to block_manager->ensure_content_created()
> line 39 of /theme/bootstrapbase/renderers/core_renderer.php: call to core_renderer->standard_head_html()
> line 52 of /theme/udimacorpclean31/layout/columns3.php: call to theme_bootstrapbase_core_renderer->standard_head_html()
> line 1028 of /lib/outputrenderers.php: call to include()
> line 958 of /lib/outputrenderers.php: call to core_renderer->render_page_layout()
> line 244 of /course/view.php: call to core_renderer->header()

Someone knows why?

Thanks!

**Comment by vfremaux** [comment]
Hi Segio, probably this is due to a PostGreSQL strictness on the boolean interpretation of the litteral 1. 
Hi ned seek for th more accurate Boolean value in the query

**Comment by SergioComeron** [comment]
yes I think that postgreSQL don't interprete the integer (1) as a boolean in this sentence: 
> ((courseid = 0 AND action = 'loggedin') OR (courseid = 0 AND action = 'loggedout') OR (1))
and then Moodle crash :(

**Comment by Erika31** [comment]
Just change :
`1`
by
`1=1`

NB: 1=1 is the shortest AND universal syntax of a TRUE condition in every SQL database.

**Comment by vfremaux** [comment]
Integrated in 35, 36? and 37 branches

Thanks for helping as PostGresSQL is not my usual test facility.
